### ISSUE TITLE
New API with required API key

### ISSUE THREAD

**Issue by Firesphere** [skx/pam_pwnd#11]
Are there plans to extend this to work with the new (paid) API from HIBP?

**Comment by skx** [comment]
I'd heard of no such API, but I would imagine not. There seem to be zero users other than myself, and I'm happy enough with it as-is.

Of course patches would be welcome to improve things, either generally, or more specifically with a new API.

**Comment by Firesphere** [comment]
Seems the older API versions are not yet fully decommissioned. You can read more about it here:
https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/

I'm actually surprised iit's still working? Troy claims to shut it down on the 18th of August this year.

**Comment by skx** [comment]
This module is designed to test if a password has been leaked.  For example to check the password `password` I calculate the SH1 hash:

```
echo -n "password" | sha1sum | tr '[a-z]' '[A-Z]'5BAA61E4C9B93F3F0682250B6CF8331B7EE68FD8  -
```

Then I take the first five characters and make a HTTP request:

```
$ curl https://api.pwnedpasswords.com/range/5BAA6 | grep -i 1E4C9B93F3F0682250B6CF8331B7EE68FD8
```

That is me searching for the rest of the hash, and in this case the password is known-bad, so we see it:

```
1E4C9B93F3F0682250B6CF8331B7EE68FD8:3730471
```

So this still works :)

**Comment by Firesphere** [comment]
Good spot! Thank you for clarifying :)

Closing this issue and TIL :)
